float:
  any:
  - base_args: ['@metric']
    constructor: MiniOBVector
    disabled: false
    docker_tag: ann-benchmarks-miniob
    module: ann_benchmarks.algorithms.miniob
    name: miniob
    run_groups:
      base:
        arg_groups: [{unix_socket: "/tmp/miniob.sock"}]
        args: {}
        query_args: [[1]]